# Site settings
title: Foss Pulchowk
name: Sujit Maharjan
email: mail@maharjansujit.com.np
description: > # this means to ignore newlines until baserurl:
  A site of Foss Pulchowk Community. This community promotes Free and Open Source Software in Pulchowk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: FrensOfAll
github_username:  shubhajeet
linkedin_username: Sujit 

# Build settings
markdown: kramdown

